# Generated by Django 3.0.6 on 2020-05-20 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('1', 'fundacja'), ('2', 'organizacja pozarządowa'), ('3', 'zbiórka lokalna')], default='1', max_length=20)),
                ('categories', models.ManyToManyField(to='give_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('adress', models.CharField(max_length=128)),
                ('phone_number', models.IntegerField(max_length=12)),
                ('city', models.CharField(max_length=36)),
                ('zip_code', models.IntegerField(max_length=6)),
                ('pick_up_comment', models.TextField(max_length=300)),
                ('categories', models.ManyToManyField(to='give_app.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='give_app.Institution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
