# Generated by Django 3.0.6 on 2020-05-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.PositiveIntegerField(choices=[('FUN', 'fundacja'), ('OP', 'organizacja pozarządowa'), ('ZL', 'zbiórka lokalna')], default='FUN'),
        ),
    ]
